- name: Setup RaspberryPI
  user: pi
  become: yes
  hosts: all
  roles:
  - common
  - net_shares
  - transmission
  - dlna

- name: Setup user shell
  user: pi
  become: no
  hosts: all
  roles:
  - homedir
