- name: "update apt cache"
  apt: update_cache=yes

- name: "setup goodies"
  apt: name={{item}}
  with_items: "{{goodies}}"

- name: "set zsh as default shell"
  user: name={{ansible_user_id}} shell=/usr/bin/zsh
